name: 'Eddie Jaoude Community Action'
description: 'Welcome first timers and maybe some badges'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
  firebase-key:
    description: 'Firebase key'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
