on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: EddieJaoudeCommunity/gh-action-community@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          repo: github
          context: context
