on:
  fork
  push:
    branches: [ develop ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review:
    types: [ submitted ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./src/welcome
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Congratulations :tada:</h1>This is your first <strong>Issue</strong>! Welcome to the community :nerd_face:'
          pr-message: '<h1>Congratulations :tada:</h1>This is your first <strong>Pull Request</strong>! Welcome to the community :nerd_face:'

  statistics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./src/statistics
        if: ${{ github.repository_owner == 'EddieJaoudeCommunity' }}
        with:
          firebase-key: ${{ secrets.FIREBASE_KEY }}
